import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Barlow_Condensed } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";

const barlow = Barlow_Condensed({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "My starter App with Next.js and Tailwind CSS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={barlow.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
