import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Barlow_Condensed } from "next/font/google";
import { cookies } from "next/headers";

const barlow = Barlow_Condensed({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "My starter App with Next.js and Tailwind CSS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = cookies().get("dark")?.value;

  return (
    <html lang="en" className={theme ? "dark" : ""}>
      <body className={barlow.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
